---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-kubectl
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-kubectl
  namespace: kube-system
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - configmaps
    verbs:
      - update
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-kubectl
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-kubectl
subjects:
  - kind: ServiceAccount
    name: test-kubectl
    namespace: kube-system
---
apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: test-kubectl
  labels:
    name: test-kubectl
    app: test-kubectl
spec:
  serviceAccountName: test-kubectl
  containers:
    - name:  kubectl
      image: vigneshsweekaran/kubectl:latest
      imagePullPolicy: Always
      command: ["sleep"]
      args: ["infinity"]

